name: flutter_labs
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+2
  connectivity_plus: ^6.0.5
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/secret.png
    - assets/user.png
    - assets/wall.png
    - assets/exit.png